org.gradle.jvmargs=-Xmx4096M
# Identity
mod_name=eureka
mod_id=vs_eureka
eureka_version=1.5.3-dev
enabled_platforms=fabric
archives_base_name=eureka
maven_group=org.valkyrienskies
# Dependencies
vs2_version=2.1.1-beta.6+a0517bae1e
vs_core_version=1.1.0+2a62e6a823
minecraft_version=1.21.8
architectury_version=9.1.8
fabric_loader_version=0.15.11
fabric_api_version=0.97.0+1.21.0
forge_version=1.21.8-0.0.0-dummy
forge_kotlin_version=3.13.0
kotlin_version=1.9.24
cloth_config_version=13.0.121
# Maven publishing
vs_maven_url=
vs_maven_username=
vs_maven_password=
# For release builds
curse_api_key=
curse_project_id=654384
modrinth_api_key=
modrinth_project_id=EO8aSHxh
